import {styleToTailwind} from "./modes/tailwindCSS"

const variantsData = [
  {
    variants: {
      "style": "basic",
      "size": "L",
      "device": "pc",
      "state": "enabled",
      "show icon": "false",
    },
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "gap": "10px",
      "padding": "11px 24px",
      "outline": "1px solid #dadada",
      "border-radius": "8px",
    },
  },
  {
    variants: {"style": "basic", "size": "L", "device": "pc", "state": "hovered", "show icon": "false"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "gap": "10px",
      "padding": "11px 24px",
      "outline": "1px solid #117ce9",
      "border-radius": "8px",
    },
  },
  {
    variants: {"style": "basic", "size": "L", "device": "pc", "state": "disabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "gap": "10px",
      "padding": "11px 24px",
      "outline": "1px solid #dadada",
      "border-radius": "8px",
    },
  },
  {
    variants: {"style": "basic", "size": "L", "device": "mobile", "state": "enabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "10px 20px",
      "outline": "1px solid #dadada",
      "border-radius": "8px",
    },
  },
  {
    variants: {"style": "basic", "size": "L", "device": "mobile", "state": "hovered", "show icon": "false"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "10px 20px",
      "outline": "1px solid #117ce9",
      "border-radius": "8px",
    },
  },
  {
    variants: {"style": "basic", "size": "L", "device": "mobile", "state": "disabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "10px 20px",
      "outline": "1px solid #dadada",
      "border-radius": "8px",
    },
  },
  {
    variants: {"style": "basic", "size": "M", "device": "pc", "state": "enabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #dadada",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic", "size": "M", "device": "pc", "state": "hovered", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #117ce9",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic", "size": "M", "device": "pc", "state": "disabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #dadada",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic", "size": "M", "device": "mobile", "state": "enabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #dadada",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic", "size": "M", "device": "mobile", "state": "hovered", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #117ce9",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic", "size": "M", "device": "mobile", "state": "disabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #dadada",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic", "size": "S", "device": "pc", "state": "enabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "outline": "1px solid #dadada",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic", "size": "S", "device": "pc", "state": "hovered", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "outline": "1px solid #117ce9",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic", "size": "S", "device": "pc", "state": "disabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "outline": "1px solid #dadada",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic", "size": "S", "device": "mobile", "state": "enabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "outline": "1px solid #dadada",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic", "size": "S", "device": "mobile", "state": "hovered", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "outline": "1px solid #117ce9",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic", "size": "S", "device": "mobile", "state": "disabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "outline": "1px solid #dadada",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic", "size": "L", "device": "pc", "state": "enabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "10px 24px",
      "outline": "1px solid #dadada",
      "border-radius": "8px",
    },
  },
  {
    variants: {"style": "basic", "size": "L", "device": "pc", "state": "hovered", "show icon": "true"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "10px 24px",
      "outline": "1px solid #117ce9",
      "border-radius": "8px",
    },
  },
  {
    variants: {"style": "basic", "size": "L", "device": "pc", "state": "disabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "10px 24px",
      "outline": "1px solid #dadada",
      "border-radius": "8px",
    },
  },
  {
    variants: {"style": "basic", "size": "L", "device": "mobile", "state": "enabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "10px 20px",
      "outline": "1px solid #dadada",
      "border-radius": "8px",
    },
  },
  {
    variants: {"style": "basic", "size": "L", "device": "mobile", "state": "hovered", "show icon": "true"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "10px 20px",
      "outline": "1px solid #117ce9",
      "border-radius": "8px",
    },
  },
  {
    variants: {"style": "basic", "size": "L", "device": "mobile", "state": "disabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "10px 20px",
      "outline": "1px solid #dadada",
      "border-radius": "8px",
    },
  },
  {
    variants: {"style": "basic", "size": "M", "device": "pc", "state": "enabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #dadada",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic", "size": "M", "device": "pc", "state": "hovered", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #117ce9",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic", "size": "M", "device": "pc", "state": "disabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #dadada",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic", "size": "M", "device": "mobile", "state": "enabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #dadada",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic", "size": "M", "device": "mobile", "state": "hovered", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #117ce9",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic", "size": "M", "device": "mobile", "state": "disabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #dadada",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic", "size": "S", "device": "pc", "state": "enabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "outline": "1px solid #dadada",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic", "size": "S", "device": "pc", "state": "hovered", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "outline": "1px solid #117ce9",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic", "size": "S", "device": "pc", "state": "disabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "outline": "1px solid #dadada",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic", "size": "S", "device": "mobile", "state": "enabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "outline": "1px solid #dadada",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic", "size": "S", "device": "mobile", "state": "hovered", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "outline": "1px solid #117ce9",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic", "size": "S", "device": "mobile", "state": "disabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "outline": "1px solid #dadada",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic_white", "size": "L", "device": "pc", "state": "enabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "10px 24px",
      "outline": "1px solid #ffffff4d",
      "border-radius": "8px",
    },
  },
  {
    variants: {"style": "basic_white", "size": "L", "device": "pc", "state": "hovered", "show icon": "false"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "10px 24px",
      "outline": "1px solid #117ce9",
      "border-radius": "8px",
    },
  },
  {
    variants: {"style": "basic_white", "size": "L", "device": "pc", "state": "disabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "10px 24px",
      "outline": "1px solid #ffffff4d",
      "border-radius": "8px",
    },
  },
  {
    variants: {"style": "basic_white", "size": "L", "device": "mobile", "state": "enabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "10px 20px",
      "outline": "1px solid #ffffff4d",
      "border-radius": "8px",
    },
  },
  {
    variants: {"style": "basic_white", "size": "L", "device": "mobile", "state": "hovered", "show icon": "false"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "10px 20px",
      "outline": "1px solid #117ce9",
      "border-radius": "8px",
    },
  },
  {
    variants: {"style": "basic_white", "size": "L", "device": "mobile", "state": "disabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "10px 20px",
      "outline": "1px solid #ffffff4d",
      "border-radius": "8px",
    },
  },
  {
    variants: {"style": "basic_white", "size": "M", "device": "pc", "state": "enabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #ffffff4d",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic_white", "size": "M", "device": "pc", "state": "hovered", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #117ce9",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic_white", "size": "M", "device": "pc", "state": "disabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #ffffff4d",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic_white", "size": "L", "device": "pc", "state": "enabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "10px 24px",
      "outline": "1px solid #ffffff4d",
      "border-radius": "8px",
    },
  },
  {
    variants: {"style": "basic_white", "size": "L", "device": "pc", "state": "hovered", "show icon": "true"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "10px 24px",
      "outline": "1px solid #117ce9",
      "border-radius": "8px",
    },
  },
  {
    variants: {"style": "basic_white", "size": "L", "device": "pc", "state": "disabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "10px 24px",
      "outline": "1px solid #ffffff4d",
      "border-radius": "8px",
    },
  },
  {
    variants: {"style": "basic_white", "size": "L", "device": "mobile", "state": "enabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "10px 20px",
      "outline": "1px solid #ffffff4d",
      "border-radius": "8px",
    },
  },
  {
    variants: {"style": "basic_white", "size": "L", "device": "mobile", "state": "hovered", "show icon": "true"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "10px 20px",
      "outline": "1px solid #117ce9",
      "border-radius": "8px",
    },
  },
  {
    variants: {"style": "basic_white", "size": "L", "device": "mobile", "state": "disabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "10px 20px",
      "outline": "1px solid #ffffff4d",
      "border-radius": "8px",
    },
  },
  {
    variants: {"style": "basic_white", "size": "M", "device": "pc", "state": "enabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #ffffff4d",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic_white", "size": "M", "device": "pc", "state": "hovered", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #117ce9",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic_white", "size": "M", "device": "pc", "state": "disabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #ffffff4d",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic_white", "size": "M", "device": "mobile", "state": "enabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #ffffff4d",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic_white", "size": "M", "device": "mobile", "state": "disabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #ffffff4d",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic_white", "size": "S", "device": "pc", "state": "enabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "outline": "1px solid #ffffff4d",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic_white", "size": "S", "device": "pc", "state": "hovered", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "outline": "1px solid #117ce9",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic_white", "size": "S", "device": "pc", "state": "disabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "outline": "1px solid #ffffff4d",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic_white", "size": "S", "device": "mobile", "state": "enabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "outline": "1px solid #ffffff4d",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic_white", "size": "S", "device": "mobile", "state": "hovered", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "outline": "1px solid #117ce9",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic_white", "size": "S", "device": "mobile", "state": "disabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "outline": "1px solid #ffffff4d",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic_white", "size": "M", "device": "mobile", "state": "hovered", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #117ce9",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic_white", "size": "M", "device": "mobile", "state": "enabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #ffffff4d",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic_white", "size": "M", "device": "mobile", "state": "hovered", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #117ce9",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic_white", "size": "M", "device": "mobile", "state": "disabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #ffffff4d",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic_white", "size": "S", "device": "pc", "state": "enabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "outline": "1px solid #ffffff4d",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic_white", "size": "S", "device": "pc", "state": "hovered", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "outline": "1px solid #117ce9",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic_white", "size": "S", "device": "pc", "state": "disabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "outline": "1px solid #ffffff4d",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic_white", "size": "S", "device": "mobile", "state": "enabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "outline": "1px solid #ffffff4d",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic_white", "size": "S", "device": "mobile", "state": "hovered", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "outline": "1px solid #117ce9",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "basic_white", "size": "S", "device": "mobile", "state": "disabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "outline": "1px solid #ffffff4d",
      "border-radius": "6px",
    },
  },
  {
    variants: {"style": "round_white", "size": "M", "device": "pc", "state": "enabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #fff",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round_white", "size": "M", "device": "pc", "state": "hovered", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #117ce9",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round_white", "size": "M", "device": "pc", "state": "disabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #ffffff4d",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round_white", "size": "M", "device": "mobile", "state": "enabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #fff",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round_white", "size": "M", "device": "mobile", "state": "hovered", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #117ce9",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round_white", "size": "M", "device": "mobile", "state": "disabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #ffffff4d",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round", "size": "L", "device": "pc", "state": "enabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 24px",
      "background": "#fff",
      "outline": "1px solid #dadada",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round", "size": "L", "device": "pc", "state": "hovered", "show icon": "false"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 24px",
      "background": "#fff",
      "outline": "1px solid #117ce9",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round", "size": "L", "device": "pc", "state": "disabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 24px",
      "background": "#ffffff26",
      "outline": "1px solid #dadada",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round", "size": "L", "device": "mobile", "state": "enabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "background": "#fff",
      "outline": "1px solid #dadada",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round", "size": "L", "device": "mobile", "state": "hovered", "show icon": "false"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "background": "#fff",
      "outline": "1px solid #117ce9",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round", "size": "L", "device": "mobile", "state": "disabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "background": "#ffffff26",
      "outline": "1px solid #dadada",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round", "size": "M", "device": "pc", "state": "enabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "background": "#fff",
      "outline": "1px solid #dadada",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round", "size": "M", "device": "pc", "state": "hovered", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "background": "#fff",
      "outline": "1px solid #117ce9",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round", "size": "M", "device": "pc", "state": "disabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "background": "#ffffff26",
      "outline": "1px solid #dadada",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round", "size": "M", "device": "mobile", "state": "enabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "background": "#fff",
      "outline": "1px solid #dadada",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round", "size": "M", "device": "mobile", "state": "hovered", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "background": "#fff",
      "outline": "1px solid #117ce9",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round", "size": "M", "device": "mobile", "state": "disabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "background": "#ffffff26",
      "outline": "1px solid #dadada",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round", "size": "S", "device": "pc", "state": "enabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "background": "#fff",
      "outline": "1px solid #dadada",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round", "size": "S", "device": "pc", "state": "hovered", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "background": "#fff",
      "outline": "1px solid #117ce9",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round", "size": "S", "device": "pc", "state": "disabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "background": "#ffffff26",
      "outline": "1px solid #dadada",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round", "size": "S", "device": "mobile", "state": "enabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "background": "#fff",
      "outline": "1px solid #dadada",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round", "size": "S", "device": "mobile", "state": "hovered", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "background": "#fff",
      "outline": "1px solid #117ce9",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round", "size": "S", "device": "mobile", "state": "disabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "background": "#ffffff26",
      "outline": "1px solid #dadada",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round", "size": "M", "device": "pc", "state": "enabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "background": "#fff",
      "outline": "1px solid #dadada",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round", "size": "M", "device": "pc", "state": "hovered", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "background": "#fff",
      "outline": "1px solid #117ce9",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round", "size": "M", "device": "pc", "state": "disabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "background": "#ffffff26",
      "outline": "1px solid #dadada",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round", "size": "M", "device": "mobile", "state": "enabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "background": "#fff",
      "outline": "1px solid #dadada",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round", "size": "M", "device": "mobile", "state": "hovered", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "background": "#fff",
      "outline": "1px solid #117ce9",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round", "size": "M", "device": "mobile", "state": "disabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "background": "#ffffff26",
      "outline": "1px solid #dadada",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round", "size": "S", "device": "pc", "state": "enabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "background": "#fff",
      "outline": "1px solid #dadada",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round", "size": "S", "device": "pc", "state": "hovered", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "background": "#fff",
      "outline": "1px solid #117ce9",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round", "size": "S", "device": "pc", "state": "disabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "background": "#ffffff26",
      "outline": "1px solid #dadada",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round", "size": "S", "device": "mobile", "state": "enabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "background": "#fff",
      "outline": "1px solid #dadada",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round", "size": "S", "device": "mobile", "state": "hovered", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "background": "#fff",
      "outline": "1px solid #117ce9",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round", "size": "S", "device": "mobile", "state": "disabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "background": "#ffffff26",
      "outline": "1px solid #dadada",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round", "size": "L", "device": "pc", "state": "enabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 24px",
      "background": "#fff",
      "outline": "1px solid #dadada",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round", "size": "L", "device": "pc", "state": "hovered", "show icon": "true"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 24px",
      "background": "#fff",
      "outline": "1px solid #117ce9",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round", "size": "L", "device": "pc", "state": "disabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 24px",
      "background": "#ffffff26",
      "outline": "1px solid #dadada",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round", "size": "L", "device": "mobile", "state": "enabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "background": "#fff",
      "outline": "1px solid #dadada",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round", "size": "L", "device": "mobile", "state": "hovered", "show icon": "true"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "background": "#fff",
      "outline": "1px solid #117ce9",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round", "size": "L", "device": "mobile", "state": "disabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "background": "#ffffff26",
      "outline": "1px solid #dadada",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round_white", "size": "L", "device": "pc", "state": "enabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 24px",
      "background": "#ffffff00",
      "outline": "1px solid #fff",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round_white", "size": "L", "device": "pc", "state": "hovered", "show icon": "false"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 24px",
      "outline": "1px solid #117ce9",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round_white", "size": "L", "device": "pc", "state": "disabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 24px",
      "outline": "1px solid #ffffff4d",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round_white", "size": "L", "device": "mobile", "state": "enabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "background": "#ffffff00",
      "outline": "1px solid #fff",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round_white", "size": "L", "device": "mobile", "state": "hovered", "show icon": "false"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #117ce9",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round_white", "size": "L", "device": "mobile", "state": "disabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #ffffff4d",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round_white", "size": "S", "device": "pc", "state": "enabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "outline": "1px solid #fff",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round_white", "size": "S", "device": "pc", "state": "hovered", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "outline": "1px solid #117ce9",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round_white", "size": "S", "device": "pc", "state": "disabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "outline": "1px solid #ffffff4d",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round_white", "size": "S", "device": "mobile", "state": "enabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "outline": "1px solid #fff",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round_white", "size": "S", "device": "mobile", "state": "hovered", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "outline": "1px solid #117ce9",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round_white", "size": "S", "device": "mobile", "state": "disabled", "show icon": "false"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "outline": "1px solid #ffffff4d",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round_white", "size": "L", "device": "pc", "state": "enabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 24px",
      "background": "#ffffff00",
      "outline": "1px solid #fff",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round_white", "size": "L", "device": "pc", "state": "hovered", "show icon": "true"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 24px",
      "outline": "1px solid #117ce9",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round_white", "size": "L", "device": "pc", "state": "disabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 24px",
      "outline": "1px solid #ffffff4d",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round_white", "size": "L", "device": "mobile", "state": "enabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "background": "#ffffff00",
      "outline": "1px solid #fff",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round_white", "size": "L", "device": "mobile", "state": "hovered", "show icon": "true"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #117ce9",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round_white", "size": "L", "device": "mobile", "state": "disabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "min-width": "140px",
      "height": "44px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #ffffff4d",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round_white", "size": "M", "device": "pc", "state": "enabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #fff",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round_white", "size": "M", "device": "pc", "state": "hovered", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #117ce9",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round_white", "size": "M", "device": "pc", "state": "disabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #ffffff4d",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round_white", "size": "M", "device": "mobile", "state": "enabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #fff",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round_white", "size": "M", "device": "mobile", "state": "hovered", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #117ce9",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round_white", "size": "M", "device": "mobile", "state": "disabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "34px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 20px",
      "outline": "1px solid #ffffff4d",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round_white", "size": "S", "device": "pc", "state": "enabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "outline": "1px solid #fff",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round_white", "size": "S", "device": "pc", "state": "hovered", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "outline": "1px solid #117ce9",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round_white", "size": "S", "device": "pc", "state": "disabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "outline": "1px solid #ffffff4d",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round_white", "size": "S", "device": "mobile", "state": "enabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "outline": "1px solid #fff",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round_white", "size": "S", "device": "mobile", "state": "hovered", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "outline": "1px solid #117ce9",
      "border-radius": "22px",
    },
  },
  {
    variants: {"style": "round_white", "size": "S", "device": "mobile", "state": "disabled", "show icon": "true"},
    style: {
      "width": "fit-content",
      "height": "30px",
      "display": "flex",
      "flex-flow": "row",
      "align-items": "center",
      "justify-content": "center",
      "padding": "11px 16px",
      "outline": "1px solid #ffffff4d",
      "border-radius": "22px",
    },
  },
]

const variantGroupProperties = {
  "style": {values: ["basic", "basic_white", "round", "round_white"]},
  "size": {values: ["L", "M", "S"]},
  "device": {values: ["pc", "mobile"]},
  "state": {values: ["enabled", "hovered", "disabled"]},
  "show icon": {values: ["false", "true"]},
}

type VariantData = {
  variants: Record<string, string>
  style: Record<string, string>
}

type VariantGroupProps = {
  [key: string]: {
    values: string[]
  }
}

export function generateCVA(variantsData: VariantData[], variantGroupProperties: VariantGroupProps) {
  // 1. Base styles 추출
  const baseStyles = styleToTailwind(extractCommonStyles(variantsData))

  // 2. 각 variant 그룹별 스타일 매핑 추출
  const variantStyleMaps = Object.keys(variantGroupProperties).reduce((acc, variantKey) => {
    acc[variantKey] = extractVariantStyles(variantsData, variantKey, variantGroupProperties[variantKey].values)
    return acc
  }, {})

  // 3. CVA 구조 생성
  return removeEmptyKeys({
    base: baseStyles,
    variants: variantStyleMaps,
    compoundVariants: extractCompoundVariants(variantsData, variantGroupProperties),
  })
}

// 빈 Array, 빈 Object만 가지고 있는 Key를 재귀적으로 찾아 제거하는 함수
function removeEmptyKeys(obj) {
  Object.keys(obj).forEach((key) => {
    if (obj[key] && typeof obj[key] === "object") {
      removeEmptyKeys(obj[key])
    }

    if (obj[key] === null || obj[key] === undefined || (typeof obj[key] === "object" && Object.keys(obj[key]).length === 0)) {
      delete obj[key]
    }
  })

  return obj
}

function extractCommonStyles(variantsData: VariantData[]) {
  // 모든 variant 조합에서 공통된 스타일 찾기
  const firstStyle = variantsData[0].style
  const commonStyles = {...firstStyle}

  variantsData.forEach(({style}) => {
    Object.keys(commonStyles).forEach((key) => {
      if (commonStyles[key] !== style[key]) {
        delete commonStyles[key]
      }
    })
  })

  return commonStyles
}

function extractVariantStyles(variantsData: VariantData[], variantKey: string, possibleValues: string[]) {
  // 특정 variant 값에 따른 스타일 변화 패턴 찾기
  const variantStyles = {}

  possibleValues.forEach((value) => {
    const relevantData = variantsData.filter((data) => data.variants[variantKey] === value)

    if (relevantData.length === 0) return

    // 이 variant 값에서만 일관되게 나타나는 스타일 찾기
    const styles = styleToTailwind(findConsistentStyles(relevantData, variantsData))
    if (Object.keys(styles).length > 0) {
      variantStyles[value] = styles
    }
  })

  return variantStyles
}

function findConsistentStyles(relevantData: VariantData[], allData: VariantData[]) {
  // 특정 variant 값에서만 일관되게 나타나는 스타일 속성 찾기
  const firstStyle = relevantData[0].style
  const consistentStyles = {}

  Object.entries(firstStyle).forEach(([key, value]) => {
    const isConsistent = relevantData.every((data) => data.style[key] === value)
    const isUnique = allData.some((data) => !relevantData.includes(data) && data.style[key] !== value)

    if (isConsistent && isUnique) {
      consistentStyles[key] = value
    }
  })

  return consistentStyles
}

function extractCompoundVariants(variantsData: VariantData[], variantGroupProperties: VariantGroupProps) {
  const compounds = []

  // 모든 가능한 variant 조합에서 특별한 스타일 규칙 찾기
  variantsData.forEach((data) => {
    const remainingStyles = {...data.style}

    // base와 일반 variant 스타일 제거
    const baseStyles = extractCommonStyles([data])
    Object.keys(baseStyles).forEach((key) => delete remainingStyles[key])

    Object.keys(data.variants).forEach((variantKey) => {
      const variantStyles = extractVariantStyles([data], variantKey, variantGroupProperties[variantKey].values)

      if (variantStyles[data.variants[variantKey]]) {
        Object.keys(variantStyles[data.variants[variantKey]]).forEach((key) => delete remainingStyles[key])
      }
    })

    // 남은 스타일이 있다면 compound variant로 추가
    if (Object.keys(remainingStyles).length > 0) {
      compounds.push({
        ...data.variants,
        className: remainingStyles,
      })
    }
  })

  return compounds
}

// const cvaConfig = generateCVA(variantsData, variantGroupProperties)
